# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules:
  - colon
  - comma
  - control_statement
  - file_length
  - type_body_length
  - line_length
  - function_body_length
  - trailing_comma
  - vertical_parameter_alignment
  - multiple_closures_with_trailing_closure
  - empty_enum_arguments
  - nesting
  - force_cast
  - identifier_name
  - large_tuple
  - number_separator
  - cyclomatic_complexity
  - function_parameter_count
  
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - private_swiftui_state
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - return_value_from_void_function
  - self_binding
  - sorted_first_last
  - sorted_imports
  - toggle_bool
  - trailing_closure
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

analyzer_rules: # rules run by `swiftlint analyze`
  - explicit_self
  - unused_declaration
  - unused_import


# Case-sensitive paths to include during linting. Directory paths supplied on the
# command line will be ignored.
included: 
  - Sources

# If true, SwiftLint will not fail if no lintable files are found.
allow_zero_lintable_files: false

# If true, SwiftLint will treat all warnings as errors.
strict: false

# If true, SwiftLint will check for updates after linting or analyzing.
check_for_updates: false

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level

# implicitly
# they can set both implicitly with an array
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)